services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - azurite-data:/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - API_PORT=3000
    depends_on:
      - azurite

  queue-listener:
    build:
      context: queue-listener
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      AzureWebJobsStorage: ${AZURE_STORAGE_CONNECTION_STRING}
    depends_on:
      - azurite

volumes:
  azurite-data:
