/* Generated by Claude Code */

import { createCanvas, loadImage } from '@napi-rs/canvas';
import type { StationMeasurement } from '@/types/buienradar.ts';

const PANEL_PADDING = 24;
const LINE_HEIGHT = 30;
const TITLE_FONT = 'bold 30px sans-serif';
const LINE_FONT = '20px sans-serif';

function formatWeatherLines(station: StationMeasurement): string[] {
  const lines: string[] = [station.weatherdescription];

  if (station.temperature !== undefined) {
    lines.push(`Temperature: ${station.temperature}°C`);
  }
  if (station.feeltemperature !== undefined) {
    lines.push(`Feels like: ${station.feeltemperature}°C`);
  }
  if (station.windspeedBft !== undefined && station.winddirection) {
    lines.push(`Wind: ${station.winddirection} (Bft ${station.windspeedBft})`);
  }
  if (station.humidity !== undefined) {
    lines.push(`Humidity: ${station.humidity}%`);
  }
  if (station.airpressure !== undefined) {
    lines.push(`Air pressure: ${station.airpressure} hPa`);
  }
  if (station.visibility !== undefined) {
    lines.push(`Visibility: ${(station.visibility / 1000).toFixed(1)} km`);
  }
  if (station.precipitation !== undefined) {
    lines.push(`Precipitation: ${station.precipitation} mm/h`);
  }

  return lines;
}

export async function generateWeatherImage(suppliedImage: Buffer, station: StationMeasurement): Promise<Buffer> {
  const image = await loadImage(suppliedImage);
  const canvas = createCanvas(image.width, image.height);
  const ctx = canvas.getContext('2d');

  ctx.drawImage(image, 0, 0, image.width, image.height);

  const lines = formatWeatherLines(station);
  const panelHeight = PANEL_PADDING * 2 + LINE_HEIGHT * (lines.length + 1);
  const panelWidth = image.width;
  const panelY = image.height - panelHeight;

  ctx.fillStyle = 'rgba(0, 0, 0, 0.55)';
  ctx.fillRect(0, panelY, panelWidth, panelHeight);

  ctx.fillStyle = '#ffffff';
  ctx.textBaseline = 'top';

  let y = panelY + PANEL_PADDING;

  ctx.font = TITLE_FONT;
  ctx.fillText(`${station.stationname} (${station.regio})`, PANEL_PADDING, y);
  y += LINE_HEIGHT + 6;

  ctx.font = LINE_FONT;
  for (const line of lines) {
    ctx.fillText(line, PANEL_PADDING, y);
    y += LINE_HEIGHT;
  }

  return canvas.toBuffer('image/png');
}
