import process from 'node:process';
import { getSasUrl, getWeatherImages } from '@shared/lib/containerClient.ts';
import { queueMessage } from '@shared/lib/queueClient.ts';
import { createJobRecord, getJobRecord } from '@shared/lib/tableClient.ts';
import { Router } from 'express';
import { v7 as uuidv7 } from 'uuid';

export const weatherRouter = Router();
const generationQueueName = process.env.GENERATION_QUEUE_NAME ?? '';

/**
 * @openapi
 * components:
 *   schemas:
 *     JobRecord:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *           format: uuid
 *         status:
 *           type: string
 *           enum: [Queued, Running, Completed, Failed]
 *         expectedStationCount:
 *           type: integer
 *         createdAt:
 *           type: string
 *           format: date-time
 *         error:
 *           type: string
 *       required:
 *         - id
 *         - status
 *         - expectedStationCount
 *         - createdAt
 */

/**
 * @openapi
 * /weather/generate:
 *   get:
 *     summary: Start a weather image generation job
 *     description: Queues a new job that generates weather station images and returns the generated job ID.
 *     tags:
 *       - Weather
 *     security:
 *      - bearerAuth: []
 *     responses:
 *       200:
 *         description: Job queued successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: success
 *                 jobId:
 *                   type: string
 *                   format: uuid
 */
weatherRouter.get('/generate', async (_req, res) => {
  const jobId = uuidv7();

  await createJobRecord(jobId);
  await queueMessage(generationQueueName, jobId);

  res.status(200).json({ status: 'success', jobId: jobId });
});

/**
 * @openapi
 * /weather/status/{id}:
 *   get:
 *     summary: Get a job's status
 *     description: Returns the job record for the given job ID.
 *     tags:
 *       - Weather
 *     security:
 *      - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: The job ID returned by /weather/generate.
 *     responses:
 *       200:
 *         description: The job record.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/JobRecord'
 *       404:
 *         description: No job exists with the given ID.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Job not found
 */
weatherRouter.get('/status/:id', async (req, res) => {
  const job = await getJobRecord(req.params.id);

  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }

  res.status(200).json(job);
});

/**
 * @openapi
 * /weather/images/{id}:
 *   get:
 *     summary: Get SAS URLs for a job's generated images
 *     description: Returns time-limited (24 hour) read-only SAS URLs for the weather images generated by the given job.
 *     tags:
 *       - Weather
 *     security:
 *      - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           format: uuid
 *         description: The job ID returned by /weather/generate.
 *     responses:
 *       200:
 *         description: SAS URLs for the job's generated images.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: string
 *                 format: uri
 *       404:
 *         description: No job exists with the given ID.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Job not found
 */
weatherRouter.get('/images/:id', async (req, res) => {
  const job = await getJobRecord(req.params.id);

  if (!job) {
    res.status(404).json({ error: 'Job not found' });
    return;
  }

  const images = await getWeatherImages(job.id);
  const imageUrls = images.map((image) => image.name);
  const imageSasUrls = await Promise.all(imageUrls.map(getSasUrl));

  res.status(200).json(imageSasUrls);
});
