/**
 * Generated by Claude Code
 *
 * Type definitions for the Buienradar JSON feed.
 * Source: https://data.buienradar.nl/2.0/feed/json
 *
 * Field selection is based on a live sample of the feed. Measurements that are
 * not reported by every weather station are marked optional.
 */

/** Root object returned by the feed. */
export interface BuienradarFeed {
  /** JSON.NET reference id, present on every object in the feed. */
  $id: string;
  buienradar: BuienradarInfo;
  actual: BuienradarActual;
  forecast: BuienradarForecast;
}

export interface BuienradarInfo {
  $id: string;
  copyright: string;
  terms: string;
}

/** Current conditions block. */
export interface BuienradarActual {
  $id: string;
  /** URL of the current national radar image. */
  actualradarurl: string;
  /** Local time, ISO 8601 without timezone, e.g. "2026-09-04T06:52:00". */
  sunrise: string;
  /** Local time, ISO 8601 without timezone. */
  sunset: string;
  stationmeasurements: StationMeasurement[];
}

/** A single weather station's most recent measurement. */
export interface StationMeasurement {
  $id: string;
  stationid: number;
  /** e.g. "Meetstation De Bilt". */
  stationname: string;
  lat: number;
  lon: number;
  /** Region label, e.g. "Utrecht". */
  regio: string;
  /** Measurement time, local, ISO 8601 without timezone. */
  timestamp: string;
  /** Dutch weather description, e.g. "Zwaar bewolkt en regen". */
  weatherdescription: string;
  /** 30x30 weather icon URL. */
  iconurl: string;
  /** 96x96 weather icon URL. */
  fullIconUrl: string;
  /** URL of the station's weather graph. */
  graphUrl: string;

  /** Compass abbreviation, e.g. "W", "WZW". */
  winddirection?: string;
  /** Wind direction in degrees, 0-360. */
  winddirectiondegrees?: number;
  /** Wind speed in m/s. */
  windspeed?: number;
  /** Wind speed on the Beaufort scale. */
  windspeedBft?: number;
  /** Wind gusts in m/s. */
  windgusts?: number;

  /** Air temperature in degrees Celsius. */
  temperature?: number;
  /** Ground temperature in degrees Celsius. */
  groundtemperature?: number;
  /** Apparent ("feels like") temperature in degrees Celsius. */
  feeltemperature?: number;

  /** Air pressure in hPa. */
  airpressure?: number;
  /** Relative humidity in percent. */
  humidity?: number;
  /** Visibility in metres. */
  visibility?: number;
  /** Solar irradiance in W/m². */
  sunpower?: number;

  /** Current precipitation in mm/h. */
  precipitation?: number;
  /** Rainfall over the last hour in mm. */
  rainFallLastHour?: number;
  /** Rainfall over the last 24 hours in mm. */
  rainFallLast24Hour?: number;
}

/** Forecast block. */
export interface BuienradarForecast {
  $id: string;
  weatherreport: WeatherReport;
  shortterm: TermForecast;
  longterm: TermForecast;
  fivedayforecast: DayForecast[];
}

export interface WeatherReport {
  $id: string;
  /** Publication time, local, ISO 8601 without timezone. */
  published: string;
  title: string;
  summary: string;
  text: string;
  author: string;
  authorbio: string;
  url: string;
}

/** Free-text short- or long-term outlook covering a date range. */
export interface TermForecast {
  $id: string;
  /** Local date, ISO 8601 without timezone. */
  startdate: string;
  /** Local date, ISO 8601 without timezone. */
  enddate: string;
  /** Free-text forecast. */
  forecast: string;
}

/** One day of the five-day forecast. */
export interface DayForecast {
  $id: string;
  /** Local date of the forecast day, ISO 8601 without timezone. */
  day: string;
  /** Minimum temperature as a string, e.g. "12". */
  mintemperature: string;
  /** Maximum temperature as a string, e.g. "19". */
  maxtemperature: string;
  mintemperatureMax: number;
  mintemperatureMin: number;
  maxtemperatureMax: number;
  maxtemperatureMin: number;
  /** Chance of rain in percent. */
  rainChance: number;
  /** Chance of sun in percent. */
  sunChance: number;
  /** Compass abbreviation, e.g. "zw". */
  windDirection: string;
  /** Wind force on the Beaufort scale. */
  wind: number;
  /** Lower bound of expected rainfall in mm. */
  mmRainMin: number;
  /** Upper bound of expected rainfall in mm. */
  mmRainMax: number;
  weatherdescription: string;
  iconurl: string;
  fullIconUrl: string;
}
