/**
 * Generated by Claude Code
 *
 * Type definitions for the Unsplash "random photo" API response.
 * Source: https://api.unsplash.com/photos/random
 *
 * Field selection is based on a live sample of the response. Collections
 * that were empty in the sample (breadcrumbs, current_user_collections,
 * topics) are typed as unknown[] since their element shape is unconfirmed.
 */

export interface UnsplashPhoto {
  id: string;
  /** Slug translated per locale, keyed by IETF language tag, e.g. "en". */
  alternative_slugs: Record<string, string>;
  created_at: string;
  updated_at: string;
  /** Set only for photos that were promoted. */
  promoted_at: string | null;
  width: number;
  height: number;
  /** Dominant color as a hex string. */
  color: string;
  /** Compact placeholder encoding blurhash.io. */
  blur_hash: string;
  description: string | null;
  /** Machine-generated description of the photo's contents. */
  alt_description: string | null;
  short_description: string | null;
  breadcrumbs: unknown[];
  urls: UnsplashPhotoUrls;
  likes: number;
  liked_by_user: boolean;
  bookmarked: boolean;
  current_user_collections: unknown[];
  sponsorship: unknown | null;
  topic_submissions: Record<string, unknown>;
  asset_type: string;
  slug: string;
  links: UnsplashPhotoLinks;
  user: UnsplashUser;
  exif: UnsplashPhotoExif;
  location: UnsplashPhotoLocation;
  meta: UnsplashPhotoMeta;
  public_domain: boolean;
  tags: UnsplashPhotoTag[];
  views: number;
  downloads: number;
  topics: unknown[];
}

/** Same image at decreasing resolutions/quality, plus a fallback on S3. */
export interface UnsplashPhotoUrls {
  raw: string;
  full: string;
  regular: string;
  small: string;
  thumb: string;
  small_s3: string;
}

export interface UnsplashPhotoLinks {
  self: string;
  html: string;
  download: string;
  download_location: string;
}

/** Camera metadata, when reported by the uploader. */
export interface UnsplashPhotoExif {
  make: string | null;
  model: string | null;
  name: string | null;
  exposure_time: string | null;
  aperture: string | null;
  focal_length: string | null;
  iso: number | null;
}

export interface UnsplashPhotoLocation {
  name: string | null;
  city: string | null;
  country: string | null;
  position: UnsplashPhotoLocationPosition;
}

export interface UnsplashPhotoLocationPosition {
  latitude: number | null;
  longitude: number | null;
}

export interface UnsplashPhotoMeta {
  index: boolean;
}

export interface UnsplashPhotoTag {
  type: string;
  title: string;
}

/** Photographer who published a photo. */
export interface UnsplashUser {
  id: string;
  updated_at: string;
  username: string;
  name: string;
  first_name: string;
  /** Absent for single-name users. */
  last_name: string | null;
  twitter_username: string | null;
  portfolio_url: string | null;
  bio: string | null;
  location: string | null;
  links: UnsplashUserLinks;
  profile_image: UnsplashProfileImage;
  instagram_username: string | null;
  total_collections: number;
  total_likes: number;
  total_photos: number;
  total_free_photos: number;
  total_promoted_photos: number;
  total_illustrations: number;
  total_free_illustrations: number;
  total_promoted_illustrations: number;
  accepted_tos: boolean;
  for_hire: boolean;
  social: UnsplashUserSocial;
}

export interface UnsplashUserLinks {
  self: string;
  html: string;
  photos: string;
  likes: string;
}

/** Square avatar at three sizes. */
export interface UnsplashProfileImage {
  small: string;
  medium: string;
  large: string;
}

export interface UnsplashUserSocial {
  instagram_username: string | null;
  portfolio_url: string | null;
  twitter_username: string | null;
  paypal_email: string | null;
}
